name: Update

on:
  schedule:
    - cron: "40 0,9,12,14,15,16,18,21 * * 1-5"
    - cron: "40 0,6,12,18 * * 0,6"
    - cron: "40 21 * * 0"
  workflow_dispatch:
    inputs:
      full:
        description: 'Full update'
        required: false
        type: boolean
      commitMessage:
        description: 'Commit message'
        required: false

jobs:
  update:
    if: github.repository == 'XeroAlpha/MinecraftHelpCenterArchive'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest
          
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Install dependencies
        run: npm install
      
      - name: Update articles
        run: node src/index.js ${{ (inputs.full || github.event.schedule == '40 21 * * 0') && 'full' || '' }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm [GMT]Z
          utcOffset: "+08:00"
      
      - name: Add safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: ${{ inputs.commitMessage || format((inputs.full || github.event.schedule == '40 21 * * 0') && 'Full update articles {0}' || 'Update articles {0}', steps.current-time.outputs.formattedTime) }}
          commit_author: "Minecraft Help <help@github.minecraft.net>"
